### ISSUE TITLE
Consider adding automated control-flow functionality

### ISSUE THREAD

**Issue by moshix** [racingmars/go3270#1]
I would like to, for example, find out if the first and last name were not filled in by the user from the handler function and if so,  set an error message in line 15 (for example) in intense to tell the user no data was put in. 

thanks a lot. Great software!

**Comment by racingmars** [comment]
Not quite sure I understand -- do you mean be able to set something like "required: true" on a field, and have the library handle checking that and display an error message instead of the application developer using the library having to check all the fields manually?

Add support for some kind of validation logic in the library itself?

**Comment by moshix** [comment]
let me explain better:

In your example.go code before this part:

response, err = go3270.ShowScreen(screen2, fieldValues, 0, 0, conn)
		if err != nil {
			fmt.Println(err)
			return
		}
I would like to set individually, say, Row 15 with some value to display before go3270.ShowScreen gets invoked. This way, I can do some plausibility checked and set some message or errorr code in a row.

Hope that simplifies my question. 

thanks

**Comment by racingmars** [comment]
Ah, I see what you mean. I think that is possible with the library already. You'd create the read-only field on row 15, perhaps setting intensity to true if that's what you want, and give it a name (say, 'errormsg'), but leave content blank. Then, if you wanted to display an error message in it, you'd add the error message to that fieldValues map before calling ShowScreen -- `fieldValues["errormsg"] = "First name is required."`

I'll update the example application to make those two fields required to see how this works.

**Comment by racingmars** [comment]
I've updated the example application with this scenario. Let me know if that's what you had in mind or if you were thinking something else.

**Comment by moshix** [comment]
Hey Matt

thanks a lot. That's actually more or less how I caught a no-input condition (well, without the loop, which is elegant!). 

Let me try to state this differently:

if we present a map (and I think in the video you hinted to the possibility of stating default values) and then the user doens't change anything to the map, it would be good if we had a flag for that so we could immediately raise an error. So, some kind of system to recognzie several flags would be great. No rush, though. 

thanks a lot!

m

**Comment by racingmars** [comment]
I think I understand what you're suggesting, but I'm trying to wrap my head around some of the practical implications.

First, let me check my understanding of your request with a proposed implementation: let's say in addition to getting the map of field values, the response also includes a "modified" variable, map[string]bool, where string is the field name, and bool is true if the user modified the field. This, to your point, isn't just blank checking: if you send the screen to the client with a default value in a field, if the user doesn't modify that default value, the modified attribute would be false, even though a value is present. [In a way, this just mirrors the MDT--modified data tag--bit for fields in the 3270 protocol.]

If that is a correct understanding of your suggestion, then my question is how to handle the following scenario:

1. You send a screen to the client with fields A and B. Your application intent is that both A and B require the user to change the value.
2. Client submits the screen, having entered a value in A but not B.
3. Your code checks modified[A] (which is true), and modified[B] (which is false). You notice modified[B] is false, populate an error message field, and send the screen back to the client to correct the error. You include the user's previous value for field A as the new default value of field A so they don't lose the partial data they've entered.
4. User fills in field B, leaving their previous (now default) value for field a.
5. This time, modified[A] would be false, and modified[B] would be true. The application using the library and checking those values might incorrect think the user hasn't fully filled out the form, unless the application remembered that last time modified[A] was true so now it's okay that we just got the default value back. But at that point...it seems the utility value of the modified indicator is pretty low, since the application would have to implement as much logic to handle that situation as it would to just do its own validation checking on values based on the modified flag.

Since each ShowScreen() call is an independent event and the library doesn't distinguish between showing the same screen to the client a second time, versus showing an entirely new screen, there isn't a way to keep the "modified" value for each field consistently meaningful across a loop of error->try again->error->try again cycles.

One more comprehensive approach would be to make the library more stateful, or give it an inherent understanding of field validators and let ShowScreen() itself be responsible for the entire show->read responses->validate fields->re-display if not all validators pass loop, so one call to ShowScreen() potentially wouldn't even return a response to the calling code until after several iterations of attempting to get the user to fill out the screen correctly. But I'm not sure if you were suggesting going that far, or if that's indeed what you had in mind...

**Comment by moshix** [comment]
Yes, I see what you mean. Actually, CICS had to deal with all these issues as well, and you are right that a more stateful. So, giving ShowScreen() ownership of show->read responses->validate fields-> re-display is very, very close to what CICS does. 

So, if I could say row 5 has a field called pick_option1 and I can say it can accept only 1 selector item alphabetic only, and only one of these group of options can be selected, then we it would be come trivial to build maps from within the application. This is obviously a lot of work to do for go3270 in the library. Another option could be to provide a seperate program that lets people design maps (like they exist for CICS) and then an include is generated which then the user application uses to send maps, get responses and process them. 

But I do think that asking the user to draw a loop for each map shown leads to very cumbersome and long user applications. Imagine if a user program has 20 maps, or more. 

thanks

M

**Comment by racingmars** [comment]
Yes, I think there's probably a need for some higher-level convenience functions in the library. The first one I was already thinking about was a "layout engine" of sorts to make it easier to build screens without having to calculate all the field positions, but I think you're right that a higher-level stateful control-flow function would be good too. I'll let that rattle around in my brain for a bit to think about how I might want to approach that.

**Comment by racingmars** [comment]
@moshix : I have added a new function, HandleScreen(), to use instead of the original ShowScreen() function. example1 in the repository is the original example, and example2 is essentially the same application but using the new HandleScreen() function so is much less code. Let me know if this is along the lines of what you were thinking to make things easier for users of the library.

There are a couple of rough edges, I'm sure, and I'd like to make things a little nicer in terms of giving the developer more control over the error messages for field validation. I'd also like to make the cursor go to the first invalid field instead of always starting at the original cursor position.

**Comment by moshix** [comment]
@racingmars Yes! much better. This spares the user to have to write a very loop for validating each screen, and instead focus on writing the logic of the panel. Let me play with this a little and I will get back. For now let's close this issue?

**Comment by racingmars** [comment]
Sounds good @moshix -- looking forward to any feedback you have!
